spring:
  profiles:
    active: local
  config:
    import:
      - classpath:jogakbo-Secrets/jwt.yml
      - classpath:jogakbo-Secrets/s3.yml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  error:
    include-message: always
---
spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:jogakbo-Secrets/db-local.yml
---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - classpath:jogakbo-Secrets/db-prod.yml
